export const portfolios = [
  {
    name: '코웨이',
    thumbnail: 'coway',
    image: ['coway_screen_1', 'coway_screen_2', 'coway_screen_3', 'coway_screen_4'],
    explain: '코웨이 입니다',
    url: 'https://www.coway.com/',
  },
  {
    name: '스마트학생복',
    thumbnail: 'smart',
    image: ['smart_screen_1', 'smart_screen_2', 'smart_screen_3', 'smart_screen_4'],
    explain: null,
    url: 'https://smartzzang.com/play/lookbook',
  },
  {
    name: 'LG Hausys',
    thumbnail: 'lg',
    image: ['lg_screen_1', 'lg_screen_2', 'lg_screen_3', 'lg_screen_4'],
    explain: null,
    url: 'https://www.lghausys-floors.co.uk/home',
  },
  {
    name: 'Instagram',
    thumbnail: 'react',
    image: ['instagram_screen_1', 'instagram_screen_2', 'instagram_screen_3'],
    explain: null,
    url: 'https://swy9112.github.io/prismagram-frontend/',
    git: 'https://github.com/swy9112/prismagram-frontend',
  },
  {
    name: 'Dashboard',
    thumbnail: 'react',
    image: ['dashboard_screen_1'],
    explain: null,
    url: 'https://swy9112.github.io/react-dashboard/',
    git: 'https://github.com/swy9112/react-dashboard',
  },
  {
    name: 'MovieApp',
    thumbnail: 'react',
    image: ['movie_screen_1', 'movie_screen_2', 'movie_screen_3'],
    explain: null,
    git: 'https://github.com/swy9112/react-native-movieapp',
  },
  { name: 'Portfolio', thumbnail: 'react' },
];
